name: 01 - CI (Test & Build Image)

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Manual trigger for the workflow
  workflow_dispatch:

jobs:
  # Tests
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push:
    name: Build and Push ${{ vars.IMAGE_NAME }}
    runs-on: ubuntu-latest

    needs: test

    # Build and push when code is pushed to main or manually triggered
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Push Docker image with commit SHA
        run: |
          docker push \
            ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}:${{ github.sha }}
