name: 02 - Deploy to Staging Slot

on:
  workflow_run:
    workflows:
      - "01 - CI (Test & Build Image)"
    types:
      - completed
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: staging

    steps:
      - name: Checkout tested commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy image to staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_NAME }}
          slot-name: staging
          images: ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}
